### ISSUE TITLE
Wait bar does not work anymore

### ISSUE THREAD

**Issue by dron-tan** [dron-tan/SpikeSimulationTool#23]
The wait bar window pops up but the loading bar does not progress at all anymore. However, the simulation still works.

**Comment by dron-tan** [comment]
Tried on HH-dev-Chris branch and the wait bar also does not work. It might be a mac thing? not quite sure. Again, simulation still works though.

**Comment by chrisoyh** [comment]
Ive tried it on my HH-dev-Chris and the wait bar works fine. It is a bit slow but thats due to the HH taking a lot of time.
