### ISSUE TITLE
2 Spikes in the Base template (templates.d) of templates_test2_array.mat

### ISSUE THREAD

**Issue by chrisoyh** [dron-tan/SpikeSimulationTool#28]
Shouldnt there only be one spike? This is the base spike used for convolution with non-transition:
![image](https://user-images.githubusercontent.com/75465737/104562601-b070c700-569c-11eb-897b-00dbbdbcd80c.png)
@dron-tan

**Comment by dron-tan** [comment]
yeah sorry i think i forgot to remove one of the parameters in the Iapp function. ill fix that when i push my changes
